### ISSUE TITLE
[BUG] Deploy Locally Failed And Methods to Resolve it.

### ISSUE THREAD

**Issue by 294916437** [AutoMQ/automq#2447]
### Version & Environment

- AutoMQ version (latest):
- Operating System (Ubuntu 22.04.4 LTS (GNU/Linux 6.8.0-58-generic x86_64):

### What went wrong?

When trying to deploy automq locally in my VMware Ubuntu 22.04.4，I firstly download docker images well and then started to run containers and invoke the problem：

✘ Container localstack  Error                                               
dependency failed to start: container localstack is unhealthy

![Image](https://github.com/user-attachments/assets/20214ee4-b98f-4f5d-a583-3551238c7663)

So，I had to check the docker-compose.yaml and found healthcheck logic, which used localstack inner check methods and failed.Then I added the custom healthcheck logic in localstack service, like this:
```
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    hostname: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack:3.3.0
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - USE_SSL=false
    volumes:
      - s3_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    # use a static ip
    networks:
      automq_net:
        ipv4_address: 10.6.0.2
    healthcheck:
      test: ["CMD-SHELL", "curl -s -k https://localhost:4566/ > /dev/null ||   exit 1"]
      interval: 15s 
      timeout: 10s 
      retries: 10 
      start_period: 90s
```
Besides，alter the install_ru.sh and delete the logic of installing logic:
```
curl -O https://download.automq.com/community_edition/standalone_deployment/docker-compose.yaml
if [ ! -f "docker-compose.yaml" ]; then
    echo "[ERROR] Docker compose yaml file not exist."
    exit 4
fi
```
to avoid writing the correct docker-compose.yaml file.
After that, I started to run the containers successfully, which didn't invoke localstack unhealthy error anymore.

![Image](https://github.com/user-attachments/assets/b2dd97ec-cfbb-4bb7-9dbe-b4e4c708e246)

### How to reproduce the issue?

1. follow the official deploy locally steps in VMware Ubuntu env
2. download docker images successfully and running containers
3. error :dependency failed to start: container localstack is unhealthy happened

### Additional information

Please attach any relevant logs, backtraces, or metric charts.
